### ISSUE TITLE
Decide on data storage mechinism

### ISSUE THREAD

**Issue by DominicEliot** [XenotropicDev/TheOracle2#3]
Discussion about how to store, create, and update game data.

Main options are:
* None (Current Oracle approach)
  * Relies on discord
  * Has a lot of extra code for parsing things
* Database
  * Requires some additional data storage
  * Has recreation advantages
  * Probably custom object advantages

**Comment by rsek** [comment]
i think customID in "stateful" Components can do a fair bit of work here; it'd also be less gross than embed fields to parse, and less likely to get messed up if someone accidentally edits the wrong field. i had good results stringifying JSON and then parsing them when receiving interactions.

customID strings are max 100 characters per button/select option, which isn't a *ton*, but still easily enough to store something like a reference to a specific oracle or a current progress track as plain text. and if there's an map/lookup table, some reasonably robust data could be pared down to a very concise JSON string.

and if we *really* want to go hogwild with cutting down customID character counts, we could do some kinda simple custom parser to avoid the various quotes, braces, etc that JSON uses. probably more trouble than it's worth unless we're routinely running up against that 100 character limit, though.

**Comment by rsek** [comment]
and FWIW: it appears that customID was implemented at least partly for this very purpose. i reckon that bodes well for the long term. <img width="990" alt="Screen Shot 2021-08-14 at 3 54 07 PM" src="https://user-images.githubusercontent.com/5354757/129462107-77e2053c-59f8-4076-a57b-5234eaac02d4.png">

**Comment by DominicEliot** [comment]
The current model (database with some help from discord) is what will be used going forward.
