### ISSUE TITLE
write class + dictionary for challenge rank data

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle2#8]
in starforged there's now several properties associated with each challenge rank (ticks marked on progress tracks, legacy ticks from expedition/bond/quest of a given rank, recommended resource hit, etc). i could centralize this in a dictionary, which could then live in the service providing other rules data.

**Comment by DominicEliot** [comment]
I'm thinking that this should still be an enum, with some helper classes around it, or a class that has the enum in one of its properties, but I'm not quite clear on the differences that would point us away from that.

**Comment by rsek** [comment]
the `Terms` array in this YAML file describes the properties associated with each challenge rank in starforged: https://github.com/rsek/dataforged/blob/main/_data-master/glossary/.todo/challenge_rank.yaml

`Value` is just a number assigned to the rank that doesn't have any concrete effects in SF. the other integers are referenced by various game mechanics.

**Comment by rsek** [comment]
i included a dictionary for this in the clocks PR, so i'll mark it as resolved for now.
